language: python
python:
  - "3.7"

install:
  - pip install flake8
  - pip install -r requirements.txt

script:
  - flake8

after_success:
  - python notify.py success

after_failure:
  - python notify.py fail
